version: "3.7"
services:
  server:
    image: tomcat
    volumes:
      - ./target/desafio-1.war:/usr/local/tomcat/webapps/desafio-1.war
    ports:
      - '8888:8080'
    environment:
      WAIT_HOSTS: mongodb:27017
    depends_on:
      - mongodb
    networks:
      - mongo-compose-network
    links:
      - mongodb
      
  mongodb:
    image: "mongo:4.4.3"
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongo
#      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017
    
    networks:
      - mongo-compose-network

  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - 8889:8081
  #   environment:
  #     ME_CONFIG_BASICAUTH_USERNAME: mongo
  #     ME_CONFIG_BASICAUTH_PASSWORD: mongo
  #     ME_CONFIG_MONGODB_PORT: 27017
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
  #   links:
  #     - mongodb
  #   networks:
  #     - mongo-compose-network
  #   depends_on:
  #     - mongodb

networks: 
    mongo-compose-network:
      driver: bridge
